trigger:
  batch: true
  branches:
    include:
      - "*"

variables:
- name: SolutionBaseName
  value: SFA.DAS.Employer.FrontDoor.Web
- name: BuildConfiguration
  value: release
- name: BuildPlatform
  value: any cpu
- group: RELEASE Management Resources
- group: RELEASE das-employers-front-door

resources:
  repositories:
  - repository: self
  - repository: das-platform-building-blocks
    type: github
    name: SkillsFundingAgency/das-platform-building-blocks
    ref: refs/tags/0.4.22
    endpoint: GitHub (SFA)
  - repository: das-platform-automation
    type: github
    name: SkillsFundingAgency/das-platform-automation
    ref: refs/tags/4.5.5
    endpoint: GitHub (SFA)
  pipelines:
  - pipeline: das-employer-config
    project: Digital Apprenticeship Service
    source: das-employer-config
    branch: das-employers-front-door-initial-config

stages:
- stage: Build
  jobs:
  - template: pipeline-templates/job/code-build.yml
    parameters:
      SolutionBaseName: $(SolutionBaseName)
      BuildConfiguration: $(BuildConfiguration)

- stage: Deploy_AT
  dependsOn: Build
  displayName: Deploy to AT
  variables:
  - group: DevTest Management Resources
  - group: AT DevTest Shared Resources
  jobs:
  - template: pipeline-templates/job/deploy.yml
    parameters:
      Environment: AT
      ServiceConnection: SFA-DAS-DevTest-ARM